# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: every day at 5am

development:
  check_duplicates:
    class: CheckDuplicatesJob
    schedule: every 5 minutes

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  check_duplicates:
    class: CheckDuplicatesJob
    schedule: every 5 minutes

  transition_projects_to_waiting_on_review:
    class: TransitionProjectsToWaitingOnReviewJob
    schedule: every day at 12am

  sync_hackatime_ban_status:
    class: SyncHackatimeBanStatusJob
    schedule: every day at 2am

  sync_users_to_airtable:
    command: "rake sync:users_to_airtable"
    schedule: every 3 hours

  # storage_maintenance:
  #   command: "rake storage:maintenance"
  #   schedule: every day at 3am

  storage_backup:
    command: "rake storage:backup"
    schedule: every day at 1am
